# Generated by Django 3.2.4 on 2021-06-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
